// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	http "github.com/goravel/framework/contracts/http"
	mock "github.com/stretchr/testify/mock"

	nethttp "net/http"

	route "github.com/goravel/framework/contracts/route"
)

// Route is an autogenerated mock type for the Route type
type Route struct {
	mock.Mock
}

// Any provides a mock function with given fields: relativePath, handler
func (_m *Route) Any(relativePath string, handler http.HandlerFunc) route.Router {
	ret := _m.Called(relativePath, handler)

	var r0 route.Router
	if rf, ok := ret.Get(0).(func(string, http.HandlerFunc) route.Router); ok {
		r0 = rf(relativePath, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(route.Router)
		}
	}

	return r0
}

// Delete provides a mock function with given fields: relativePath, handler
func (_m *Route) Delete(relativePath string, handler http.HandlerFunc) route.Router {
	ret := _m.Called(relativePath, handler)

	var r0 route.Router
	if rf, ok := ret.Get(0).(func(string, http.HandlerFunc) route.Router); ok {
		r0 = rf(relativePath, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(route.Router)
		}
	}

	return r0
}

// Fallback provides a mock function with given fields: handler
func (_m *Route) Fallback(handler http.HandlerFunc) {
	_m.Called(handler)
}

// Get provides a mock function with given fields: relativePath, handler
func (_m *Route) Get(relativePath string, handler http.HandlerFunc) route.Router {
	ret := _m.Called(relativePath, handler)

	var r0 route.Router
	if rf, ok := ret.Get(0).(func(string, http.HandlerFunc) route.Router); ok {
		r0 = rf(relativePath, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(route.Router)
		}
	}

	return r0
}

// GetRoute provides a mock function with given fields: name, params
func (_m *Route) GetRoute(name string, params ...map[string]interface{}) string {
	_va := make([]interface{}, len(params))
	for _i := range params {
		_va[_i] = params[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, ...map[string]interface{}) string); ok {
		r0 = rf(name, params...)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GlobalMiddleware provides a mock function with given fields: middlewares
func (_m *Route) GlobalMiddleware(middlewares ...http.Middleware) {
	_va := make([]interface{}, len(middlewares))
	for _i := range middlewares {
		_va[_i] = middlewares[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Group provides a mock function with given fields: handler
func (_m *Route) Group(handler route.GroupFunc) {
	_m.Called(handler)
}

// Middleware provides a mock function with given fields: middlewares
func (_m *Route) Middleware(middlewares ...http.Middleware) route.Router {
	_va := make([]interface{}, len(middlewares))
	for _i := range middlewares {
		_va[_i] = middlewares[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 route.Router
	if rf, ok := ret.Get(0).(func(...http.Middleware) route.Router); ok {
		r0 = rf(middlewares...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(route.Router)
		}
	}

	return r0
}

// Name provides a mock function with given fields: name
func (_m *Route) Name(name string) route.Router {
	ret := _m.Called(name)

	var r0 route.Router
	if rf, ok := ret.Get(0).(func(string) route.Router); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(route.Router)
		}
	}

	return r0
}

// Options provides a mock function with given fields: relativePath, handler
func (_m *Route) Options(relativePath string, handler http.HandlerFunc) route.Router {
	ret := _m.Called(relativePath, handler)

	var r0 route.Router
	if rf, ok := ret.Get(0).(func(string, http.HandlerFunc) route.Router); ok {
		r0 = rf(relativePath, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(route.Router)
		}
	}

	return r0
}

// Patch provides a mock function with given fields: relativePath, handler
func (_m *Route) Patch(relativePath string, handler http.HandlerFunc) route.Router {
	ret := _m.Called(relativePath, handler)

	var r0 route.Router
	if rf, ok := ret.Get(0).(func(string, http.HandlerFunc) route.Router); ok {
		r0 = rf(relativePath, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(route.Router)
		}
	}

	return r0
}

// Post provides a mock function with given fields: relativePath, handler
func (_m *Route) Post(relativePath string, handler http.HandlerFunc) route.Router {
	ret := _m.Called(relativePath, handler)

	var r0 route.Router
	if rf, ok := ret.Get(0).(func(string, http.HandlerFunc) route.Router); ok {
		r0 = rf(relativePath, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(route.Router)
		}
	}

	return r0
}

// Prefix provides a mock function with given fields: addr
func (_m *Route) Prefix(addr string) route.Router {
	ret := _m.Called(addr)

	var r0 route.Router
	if rf, ok := ret.Get(0).(func(string) route.Router); ok {
		r0 = rf(addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(route.Router)
		}
	}

	return r0
}

// Put provides a mock function with given fields: relativePath, handler
func (_m *Route) Put(relativePath string, handler http.HandlerFunc) route.Router {
	ret := _m.Called(relativePath, handler)

	var r0 route.Router
	if rf, ok := ret.Get(0).(func(string, http.HandlerFunc) route.Router); ok {
		r0 = rf(relativePath, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(route.Router)
		}
	}

	return r0
}

// Resource provides a mock function with given fields: relativePath, controller
func (_m *Route) Resource(relativePath string, controller http.ResourceController) route.Router {
	ret := _m.Called(relativePath, controller)

	var r0 route.Router
	if rf, ok := ret.Get(0).(func(string, http.ResourceController) route.Router); ok {
		r0 = rf(relativePath, controller)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(route.Router)
		}
	}

	return r0
}

// Run provides a mock function with given fields: host
func (_m *Route) Run(host ...string) error {
	_va := make([]interface{}, len(host))
	for _i := range host {
		_va[_i] = host[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...string) error); ok {
		r0 = rf(host...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RunTLS provides a mock function with given fields: host
func (_m *Route) RunTLS(host ...string) error {
	_va := make([]interface{}, len(host))
	for _i := range host {
		_va[_i] = host[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...string) error); ok {
		r0 = rf(host...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RunTLSWithCert provides a mock function with given fields: host, certFile, keyFile
func (_m *Route) RunTLSWithCert(host string, certFile string, keyFile string) error {
	ret := _m.Called(host, certFile, keyFile)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(host, certFile, keyFile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServeHTTP provides a mock function with given fields: writer, request
func (_m *Route) ServeHTTP(writer nethttp.ResponseWriter, request *nethttp.Request) {
	_m.Called(writer, request)
}

// Static provides a mock function with given fields: relativePath, root
func (_m *Route) Static(relativePath string, root string) {
	_m.Called(relativePath, root)
}

// StaticFS provides a mock function with given fields: relativePath, fs
func (_m *Route) StaticFS(relativePath string, fs nethttp.FileSystem) {
	_m.Called(relativePath, fs)
}

// StaticFile provides a mock function with given fields: relativePath, filepath
func (_m *Route) StaticFile(relativePath string, filepath string) {
	_m.Called(relativePath, filepath)
}

type mockConstructorTestingTNewRoute interface {
	mock.TestingT
	Cleanup(func())
}

// NewRoute creates a new instance of Route. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRoute(t mockConstructorTestingTNewRoute) *Route {
	mock := &Route{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
